WITH customerSubscriptionDetails AS (
    SELECT
        WCC.ID AS CUSTOMER_ID,
        CASE
            WHEN WRCS.STATUS='CANCELLED' THEN 'CANCELLED'
            WHEN WRCS.STATUS='PAUSED' THEN 'PAUSED'
            WHEN WRCS.STATUS='REJECTED' THEN 'REJECTED'
            WHEN WRCS.STATUS='CORRUPTED' THEN 'PAUSED'
            WHEN WRCS.STATUS='FLAGGED' THEN 'FLAGGED'
            ELSE 'ACTIVE'
        END AS SUBSCRIPTION_STATUS
    FROM WALDO_CUSTOMERS.CUSTOMER WCC
    JOIN WALDO_RENEWALS.CUSTOMERSUBSCRIPTION WRCS ON WCC.ID = WRCS.CUSTOMERID
),
customerCancellationDetails AS (
    SELECT
        WCC.ID AS CUSTOMER_ID,
        MAX(WRC.CREATEDAT) AS LAST_CANCELLATION_DATE
    FROM WALDO_CUSTOMERS.CUSTOMER WCC
    JOIN WALDO_RENEWALS.CUSTOMERSUBSCRIPTION WRCS ON WCC.ID = WRCS.CUSTOMERID
    JOIN WALDO_RENEWALS.CANCELLATION WRC ON WRCS.ID = WRC.CUSTOMERSUBSCRIPTIONID
    GROUP BY WCC.ID
),
customerPauseDetails AS (
    SELECT
        WCC.ID AS CUSTOMER_ID,
        MAX(WRP.CREATEDAT) AS LAST_PAUSE_DATE
    FROM WALDO_CUSTOMERS.CUSTOMER WCC
    JOIN WALDO_RENEWALS.CUSTOMERSUBSCRIPTION WRCS ON WCC.ID = WRCS.CUSTOMERID
    JOIN WALDO_RENEWALS.PAUSE WRP ON WRCS.ID = WRP.CUSTOMERSUBSCRIPTIONID
    GROUP BY WCC.ID
),
customerOTPDetails AS (
    SELECT
        WCC.ID AS CUSTOMER_ID,
        COUNT(WOC.ID) AS NUM_OTP_ORDERS,
        SUM(WOO.GRANDTOTALPRICE) AS TOTAL_OTP_SPEND,
        MAX(WOC.CREATEDAT) AS LAST_OTP_ORDER
    FROM WALDO_CUSTOMERS.CUSTOMER WCC
    JOIN WALDO_ORDERS.ORDERCUSTOMER WOOC ON WCC.ID = WOOC.CUSTOMERID
    JOIN WALDO_ORDERS."ORDER" WOO ON WOOC.ORDERID = WOO.ID
    JOIN WALDO_ORDERS.CHARGE WOC ON WOO.ID = WOC.ORDERID
    WHERE WOC.STATUS = 'SUCCESS' AND WOO.TAGS LIKE '%otp%'
    GROUP BY WCC.ID
),
customerTrialDetails AS (
    SELECT
        WCC.ID AS CUSTOMER_ID,
        COUNT(WOC.ID) AS NUM_TRIAL_ORDERS,
        SUM(WOO.GRANDTOTALPRICE) AS TOTAL_TRIAL_SPEND,
        MAX(WOO.CREATEDAT) AS LAST_TRIAL_ORDER
    FROM WALDO_CUSTOMERS.CUSTOMER WCC
    JOIN WALDO_ORDERS.ORDERCUSTOMER WOOC ON WCC.ID = WOOC.CUSTOMERID
    JOIN WALDO_ORDERS."ORDER" WOO ON WOOC.ORDERID = WOO.ID
    JOIN WALDO_ORDERS.CHARGE WOC ON WOO.ID = WOC.ORDERID
    WHERE WOC.STATUS = 'SUCCESS' AND (
        WOO.TAGS LIKE '%trial%'
        OR (
            -- checks if otp since otp tags did not exist before 07-14-2022
            WOO.GRANDTOTALPRICE < 2000
            AND WOO.CREATEDAT < '2022-07-14 22:42:12.651000000 +00:00'
        )
    )
    GROUP BY WCC.ID
),
customerRenewalDetails AS (
    SELECT
        WCC.ID AS CUSTOMER_ID,
        COUNT(WOC.ID) AS NUM_RENEWAL_ORDERS,
        SUM(WOO.GRANDTOTALPRICE) AS TOTAL_RENEWAL_SPEND,
        MAX(WOC.CREATEDAT) AS LAST_RENEWAL_ORDER
    FROM WALDO_CUSTOMERS.CUSTOMER WCC
    JOIN WALDO_ORDERS.ORDERCUSTOMER WOOC ON WCC.ID = WOOC.CUSTOMERID
    JOIN WALDO_ORDERS."ORDER" WOO ON WOOC.ORDERID = WOO.ID
    JOIN WALDO_ORDERS.CHARGE WOC ON WOO.ID = WOC.ORDERID
    WHERE WOC.STATUS = 'SUCCESS' AND (
        WOO.TAGS LIKE '%renewal%'
        OR (
            WOO.TAGS NOT LIKE '%otp%' AND WOO.TAGS NOT LIKE '%trial%'
        )
        OR (
            WOO.CREATEDAT < '2022-07-14 22:42:12.651000000 +00:00' AND WOO.GRANDTOTALPRICE > 2000
        )
        )
    -- could add NOT LIKE 'OTP' NOT LIKE 'TRIAL' before 2022-07-14 22:42:12.651000000 +00:00
    -- grandprice >= 2000
    GROUP BY WCC.ID
),
customerOrderDetails AS (
    SELECT
        WCC.ID AS CUSTOMER_ID,
        COUNT(WOC.ID) AS NUM_ORDERS,
        SUM(WOO.GRANDTOTALPRICE) AS TOTAL_SPEND,
        MAX(WOC.CREATEDAT) AS LAST_ORDER
    FROM WALDO_CUSTOMERS.CUSTOMER WCC
    JOIN WALDO_ORDERS.ORDERCUSTOMER WOOC ON WCC.ID = WOOC.CUSTOMERID
    JOIN WALDO_ORDERS."ORDER" WOO ON WOOC.ORDERID = WOO.ID
    JOIN WALDO_ORDERS.CHARGE WOC ON WOO.ID = WOC.ORDERID
    WHERE WOC.STATUS = 'SUCCESS'
    GROUP BY WCC.ID
)
SELECT
    WCC.ID AS CUSTOMER_ID,
    TO_CHAR(WCC.CREATEDAT, 'YYYY-MM-DD') AS START_DATE,
    WCC.EMAIL,
    CSD.SUBSCRIPTION_STATUS,
    CCD.LAST_CANCELLATION_DATE,
    CPD.LAST_PAUSE_DATE,
    COD.LAST_OTP_ORDER,
    COD.NUM_OTP_ORDERS,
    COD.TOTAL_OTP_SPEND,
    CTD.LAST_TRIAL_ORDER,
    CTD.NUM_TRIAL_ORDERS,
    CTD.TOTAL_TRIAL_SPEND,
    CRD.LAST_RENEWAL_ORDER,
    CRD.NUM_RENEWAL_ORDERS,
    CRD.TOTAL_RENEWAL_SPEND,
    CAD.LAST_ORDER,
    CAD.NUM_ORDERS,
    CAD.TOTAL_SPEND
FROM WALDO_CUSTOMERS.CUSTOMER AS WCC
FULL OUTER JOIN customerSubscriptionDetails AS CSD ON WCC.ID = CSD.CUSTOMER_ID
FULL OUTER JOIN customerCancellationDetails AS CCD ON WCC.ID = CCD.CUSTOMER_ID
FULL OUTER JOIN customerPauseDetails AS CPD ON WCC.ID = CPD.CUSTOMER_ID
FULL OUTER JOIN customerOTPDetails AS COD ON WCC.ID = COD.CUSTOMER_ID
FULL OUTER JOIN customerTrialDetails AS CTD ON WCC.ID = CTD.CUSTOMER_ID
FULL OUTER JOIN customerRenewalDetails AS CRD ON WCC.ID = CRD.CUSTOMER_ID
FULL OUTER JOIN customerOrderDetails AS CAD ON WCC.ID = CAD.CUSTOMER_ID
WHERE WCC.REGION = 'US' AND NUM_TRIAL_ORDERS IS NULL AND NUM_RENEWAL_ORDERS >= 1;
-- ORDER BY NUM_TRIAL_ORDERS, NUM_RENEWAL_ORDERS
-- ORDER BY WCC.ID;
-- WCC.EMAIL = 'samdee1210@gmail.com' should have trials = 1/2


-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------

WITH customerSubscriptionDetails AS (
    SELECT
        WCC.ID AS CUSTOMER_ID,
        CASE
            WHEN WRCS.STATUS='CANCELLED' THEN 'CANCELLED'
            WHEN WRCS.STATUS='PAUSED' THEN 'PAUSED'
            WHEN WRCS.STATUS='REJECTED' THEN 'REJECTED'
            WHEN WRCS.STATUS='CORRUPTED' THEN 'PAUSED'
            WHEN WRCS.STATUS='FLAGGED' THEN 'FLAGGED'
            ELSE 'ACTIVE'
        END AS SUBSCRIPTION_STATUS
    FROM WALDO_CUSTOMERS.CUSTOMER WCC
    FULL OUTER JOIN WALDO_RENEWALS.CUSTOMERSUBSCRIPTION WRCS ON WCC.ID = WRCS.CUSTOMERID
),
customerCancellationDetails AS (
    SELECT
        WCC.ID AS CUSTOMER_ID,
        MAX(WRC.CREATEDAT) AS LAST_CANCELLATION_DATE
    FROM WALDO_CUSTOMERS.CUSTOMER WCC
    FULL OUTER JOIN WALDO_RENEWALS.CUSTOMERSUBSCRIPTION WRCS ON WCC.ID = WRCS.CUSTOMERID
    FULL OUTER JOIN WALDO_RENEWALS.CANCELLATION WRC ON WRCS.ID = WRC.CUSTOMERSUBSCRIPTIONID
    GROUP BY WCC.ID
),
customerPauseDetails AS (
    SELECT
        WCC.ID AS CUSTOMER_ID,
        MAX(WRP.CREATEDAT) AS LAST_PAUSE_DATE
    FROM WALDO_CUSTOMERS.CUSTOMER WCC
    FULL OUTER JOIN WALDO_RENEWALS.CUSTOMERSUBSCRIPTION WRCS ON WCC.ID = WRCS.CUSTOMERID
    FULL OUTER JOIN WALDO_RENEWALS.PAUSE WRP ON WRCS.ID = WRP.CUSTOMERSUBSCRIPTIONID
    GROUP BY WCC.ID
),
customerOTPDetails AS (
    SELECT
        WCC.ID AS CUSTOMER_ID,
        COUNT(WOO.ID) AS NUM_OTP_ORDERS,
        SUM(WOO.GRANDTOTALPRICE) AS TOTAL_OTP_SPEND,
        MAX(WOO.CREATEDAT) AS LAST_OTP_ORDER,
        MAX(WOC.CREATEDAT) AS LAST_OTP_CHARGE
    FROM WALDO_CUSTOMERS.CUSTOMER WCC
    FULL OUTER JOIN WALDO_ORDERS.ORDERCUSTOMER WOOC ON WCC.ID = WOOC.CUSTOMERID
    FULL OUTER JOIN WALDO_ORDERS."ORDER" WOO ON WOOC.ORDERID = WOO.ID
    FULL OUTER JOIN WALDO_ORDERS.CHARGE WOC ON WOO.ID = WOC.ORDERID
    WHERE WOO.STATUS NOT IN ('REJECTED', 'BYPASSED', 'FAILURE', 'INFERRED') AND WOO.TAGS LIKE '%otp%' AND WOO.GRANDTOTALPRICE >= 2000
    GROUP BY WCC.ID
),
customerTrialDetails AS (
    SELECT
        WCC.ID AS CUSTOMER_ID,
        COUNT(WOO.ID) AS NUM_TRIAL_ORDERS,
        SUM(WOO.GRANDTOTALPRICE) AS TOTAL_TRIAL_SPEND,
        MAX(WOO.CREATEDAT) AS LAST_TRIAL_ORDER,
        MAX(WOC.CREATEDAT) AS LAST_TRIAL_CHARGE
    FROM WALDO_CUSTOMERS.CUSTOMER WCC
    FULL OUTER JOIN WALDO_ORDERS.ORDERCUSTOMER WOOC ON WCC.ID = WOOC.CUSTOMERID
    FULL OUTER JOIN WALDO_ORDERS."ORDER" WOO ON WOOC.ORDERID = WOO.ID
    FULL OUTER JOIN WALDO_ORDERS.CHARGE WOC ON WOO.ID = WOC.ORDERID
    WHERE WOO.STATUS NOT IN ('REJECTED', 'BYPASSED', 'FAILURE', 'INFERRED') AND (
        WOO.TAGS LIKE '%trial%' OR
        WOO.GRANDTOTALPRICE < 2000
    )
    GROUP BY WCC.ID
),
customerRenewalDetails AS (
    SELECT
        WCC.ID AS CUSTOMER_ID,
        COUNT(WOO.ID) AS NUM_RENEWAL_ORDERS,
        SUM(WOO.GRANDTOTALPRICE) AS TOTAL_RENEWAL_SPEND,
        MAX(WOO.CREATEDAT) AS LAST_RENEWAL_ORDER,
        MAX(WOC.CREATEDAT) AS LAST_RENEWAL_CHARGE
    FROM WALDO_CUSTOMERS.CUSTOMER WCC
    FULL OUTER JOIN WALDO_ORDERS.ORDERCUSTOMER WOOC ON WCC.ID = WOOC.CUSTOMERID
    FULL OUTER JOIN WALDO_ORDERS."ORDER" WOO ON WOOC.ORDERID = WOO.ID
    FULL OUTER JOIN WALDO_ORDERS.CHARGE WOC ON WOO.ID = WOC.ORDERID
    WHERE WOO.STATUS NOT IN ('REJECTED', 'BYPASSED', 'FAILURE', 'INFERRED') AND (
        WOO.TAGS NOT LIKE '%otp%' AND
        WOO.TAGS NOT LIKE '%trial%' OR (
            WOO.GRANDTOTALPRICE >= 2000 AND
            WOO.CREATEDAT < '2022-07-14 22:42:12.651'
        )
    )
    GROUP BY WCC.ID
),
customerOrderDetails AS (
    SELECT
        WCC.ID AS CUSTOMER_ID,
        COUNT(WOO.ID) AS NUM_ORDERS,
        SUM(WOO.GRANDTOTALPRICE) AS TOTAL_SPEND,
        MAX(WOO.CREATEDAT) AS LAST_ORDER,
        MAX(WOC.CREATEDAT) AS LAST_CHARGE
    FROM WALDO_CUSTOMERS.CUSTOMER WCC
    FULL OUTER JOIN WALDO_ORDERS.ORDERCUSTOMER WOOC ON WCC.ID = WOOC.CUSTOMERID
    FULL OUTER JOIN WALDO_ORDERS."ORDER" WOO ON WOOC.ORDERID = WOO.ID
    FULL OUTER JOIN WALDO_ORDERS.CHARGE WOC ON WOO.ID = WOC.ORDERID
    WHERE WOO.STATUS NOT IN ('REJECTED', 'BYPASSED', 'FAILURE', 'INFERRED')
    GROUP BY WCC.ID
)
SELECT
    WCC.ID AS CUSTOMER_ID,
    WCC.EMAIL,
    WCC.CREATEDAT,
    CSD.SUBSCRIPTION_STATUS,
    CCD.LAST_CANCELLATION_DATE,
    CPD.LAST_PAUSE_DATE,
    COD.NUM_OTP_ORDERS,
    COD.TOTAL_OTP_SPEND,
    COD.LAST_OTP_ORDER,
    CTD.NUM_TRIAL_ORDERS,
    CTD.TOTAL_TRIAL_SPEND,
    CTD.LAST_TRIAL_ORDER,
    CTD.LAST_TRIAL_CHARGE,
    CRD.NUM_RENEWAL_ORDERS,
    CRD.TOTAL_RENEWAL_SPEND,
    CRD.LAST_RENEWAL_ORDER,
    CRD.LAST_RENEWAL_CHARGE,
    CAD.NUM_ORDERS,
    CAD.TOTAL_SPEND,
    CAD.LAST_ORDER,
    CAD.LAST_CHARGE
FROM WALDO_CUSTOMERS.CUSTOMER AS WCC
FULL OUTER JOIN customerSubscriptionDetails AS CSD ON WCC.ID = CSD.CUSTOMER_ID
FULL OUTER JOIN customerCancellationDetails AS CCD ON WCC.ID = CCD.CUSTOMER_ID
FULL OUTER JOIN customerPauseDetails AS CPD ON WCC.ID = CPD.CUSTOMER_ID
FULL OUTER JOIN customerOTPDetails AS COD ON WCC.ID = COD.CUSTOMER_ID
FULL OUTER JOIN customerTrialDetails AS CTD ON WCC.ID = CTD.CUSTOMER_ID
FULL OUTER JOIN customerRenewalDetails AS CRD ON WCC.ID = CRD.CUSTOMER_ID
FULL OUTER JOIN customerOrderDetails AS CAD ON WCC.ID = CAD.CUSTOMER_ID
WHERE WCC.REGION = 'US' AND NUM_TRIAL_ORDERS = 1
ORDER BY WCC.ID