--credit_remaining_by_month_year
WITH ALL_INFO AS (
WITH Region_Currency AS (
    SELECT DISTINCT REGION, CURRENCY
    FROM WALDO_ORDERS.CHARGE woc
),
Active_Customers_3_years AS (
    SELECT
    wcc.ID,
    MAX(TO_CHAR(woc.CREATEDAT, 'YYYY-MM-DD')) LAST_ORDER,
    wcc.REGION,
    woc.CURRENCY,
    wcc.CREDIT
    FROM WALDO_CUSTOMERS.CUSTOMER wcc
    JOIN WALDO_ORDERS.ORDERCUSTOMER wooc on wcc.ID = wooc.CUSTOMERID
    JOIN WALDO_ORDERS.CHARGE woc on wooc.ORDERID = woc.ORDERID AND wcc.REGION = woc.REGION
    WHERE EMAIL LIKE '%@%'
    AND EMAIL NOT LIKE '%@hiwaldo%'
    AND LOWER(FIRSTNAME) NOT LIKE '%test%'
    AND LOWER(LASTNAME) NOT LIKE '%test%'
    AND woc.STATUS = 'SUCCESS'
    AND TO_CHAR(woc.CREATEDAT, 'YYYY-MM') >= '2021-01' --DATEADD(YEAR, -3, CURRENT_DATE())  -- '2024-04-30')
    GROUP BY wcc.ID, wcc.REGION, woc.CURRENCY, wcc.CREDIT
    ORDER BY LAST_ORDER
),
Credit_Unused AS (
    SELECT wcc.REGION, SUM(wcc.CREDIT/100) UNUSED_CREDIT
    FROM WALDO_CUSTOMERS.CUSTOMER wcc
    WHERE EMAIL LIKE '%@%'
    AND EMAIL NOT LIKE '%@hiwaldo%'
    AND LOWER(FIRSTNAME) NOT LIKE '%test%'
    AND LOWER(LASTNAME) NOT LIKE '%test%'
    AND wcc.ID IN (SELECT DISTINCT ac.ID FROM Active_Customers_3_years ac)
    GROUP BY wcc.REGION
),
Used_Credit_Month_Year AS (
SELECT
    wcc.REGION,
    TO_CHAR(woc.CREATEDAT, 'YYYY-MM') AS month_year,
    COUNT(DISTINCT wcc.ID) AS "TOTAL_CUSTOMER_COUNT",
    ROUND(SUM(woo.CREDITDEDUCTIONS/100), 2) AS "TOTAL_CREDIT_USED"
FROM
    WALDO_CUSTOMERS.CUSTOMER wcc
JOIN WALDO_ORDERS.ORDERCUSTOMER wooc on wcc.ID = wooc.CUSTOMERID
JOIN WALDO_ORDERS."ORDER" woo on wooc.ORDERID = woo.ID
JOIN WALDO_ORDERS.CHARGE woc on woo.ID = woc.ORDERID
WHERE
    TO_CHAR(woc.CREATEDAT, 'YYYY-MM') BETWEEN '2021-01' AND '2024-05'
    AND EMAIL LIKE '%@%'
    AND EMAIL NOT LIKE '%@hiwaldo%'
    AND LOWER(FIRSTNAME) NOT LIKE '%test%'
    AND LOWER(LASTNAME) NOT LIKE '%test%'
    AND wcc.ACTIVE = TRUE
    AND woc.STATUS = 'SUCCESS'
    AND woo.status in ('SUCCESS','APPROVED','DISPATCHING')
    AND wcc.ID IN (SELECT ac.ID FROM Active_Customers_3_years ac)
GROUP BY
    wcc.REGION,
    TO_CHAR(woc.CREATEDAT, 'YYYY-MM')
ORDER BY
    month_year
),
Credit_Used_May as (
SELECT wcc.REGION,
       COUNT(DISTINCT CASE WHEN VALUEADDED < 0 THEN wcc.ID END) as "TOTAL_CUSTOMER_COUNT",
       ROUND(SUM(CASE WHEN VALUEADDED < 0 THEN -1 * VALUEADDED/100 END),2) as "TOTAL_CREDIT_USED"
FROM WALDO_CUSTOMERS.CUSTOMER wcc
JOIN WALDO_CUSTOMERS.CUSTOMERCREDITLOG wccl ON wcc.ID = wccl.CUSTOMERID
JOIN WALDO_ORDERS.CHARGE woc on wccl.ORDERID = woc.ORDERID
WHERE TO_CHAR(wccl.CREATEDAT, 'YYYY-MM-DD') BETWEEN '2024-05-01' AND TO_CHAR(CURRENT_DATE(), 'YYYY-MM-DD')
AND EMAIL LIKE '%@%'
AND EMAIL NOT LIKE '%@hiwaldo%'
AND LOWER(FIRSTNAME) NOT LIKE '%test%'
AND LOWER(LASTNAME) NOT LIKE '%test%'
AND wcc.ACTIVE = true
AND woc.STATUS = 'SUCCESS'
GROUP BY wcc.REGION
)
SELECT my.month_year, my.REGION, rc.CURRENCY,
       my.TOTAL_CREDIT_USED, cu.UNUSED_CREDIT,
       my.TOTAL_CUSTOMER_COUNT,
       SUM(my.TOTAL_CREDIT_USED) OVER (PARTITION BY my.REGION ORDER BY my.month_year DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
            + cu.UNUSED_CREDIT AS CUMULATIVE_CREDIT_WITH_UNUSED
FROM Used_Credit_Month_Year my
    JOIN Region_Currency rc on my.REGION = rc.REGION
    JOIN Credit_Unused cu on my.REGION = cu.REGION
-- GROUP BY my.month_year, my.REGION, rc.CURRENCY, my.TOTAL_CREDIT_USED, cu.UNUSED_CREDIT, my.TOTAL_CUSTOMER_COUNT
ORDER BY month_year, my.REGION )
SELECT ai.month_year, ai.REGION, ai.CURRENCY,
       ai.TOTAL_CREDIT_USED,
       -- ai.UNUSED_CREDIT, CUMULATIVE_CREDIT_WITH_UNUSED,
       LAG(ROUND(ai.CUMULATIVE_CREDIT_WITH_UNUSED,2), 1, ROUND(ai.UNUSED_CREDIT,2))
        OVER (PARTITION BY ai.REGION ORDER BY ai.month_year DESC) AS CUMULATIVE_UNUSED_CREDIT,
        ai.TOTAL_CUSTOMER_COUNT
FROM ALL_INFO ai
ORDER BY month_year DESC, REGION;