-- Revenue_past_4_weeks
WITH Weeks AS (
  SELECT
    TO_CHAR(DATEADD(DAY, 7 * (ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1), '2024-03-04'), 'YYYY-MM-DD') AS Week_Start_Date,
    TO_CHAR(DATEADD(DAY, 6, DATEADD(DAY, 7 * (ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1), '2024-03-04')), 'YYYY-MM-DD') AS Week_End_Date
  FROM
    TABLE(GENERATOR(ROWCOUNT => 4)) -- generate 'x' weeks
)
SELECT
  Weeks.Week_Start_Date AS Start_Date,
  Weeks.Week_End_Date AS End_Date,
  COALESCE(SUM(WOO.GRANDTOTALPRICE), 0) AS Total_Revenue,
  COALESCE(SUM(CASE WHEN WRCS.STATUS = 'CANCELLED' THEN 1 ELSE 0 END), 0) AS Cancelled_Subscriptions,
  ROUND(COALESCE(CAST(SUM(CASE WHEN WRCS.STATUS = 'CANCELLED' THEN 1 ELSE 0 END) AS FLOAT) /
           NULLIF(COUNT(*), 0), 0) * 100, 2) AS Churn_Percent

FROM
  Weeks
LEFT JOIN
  WALDO_ORDERS."ORDER" WOO ON TO_CHAR(WOO.CREATEDAT, 'YYYY-MM-DD') BETWEEN Weeks.Week_Start_Date AND Weeks.Week_End_Date
INNER JOIN WALDO_ORDERS.ORDERCUSTOMER WOOC ON WOO.ID = WOOC.ORDERID
INNER JOIN WALDO_CUSTOMERS.CUSTOMER WCC ON WOOC.CUSTOMERID = WCC.ID
INNER JOIN WALDO_RENEWALS.CUSTOMERSUBSCRIPTION WRCS ON WRCS.CUSTOMERID = WCC.ID

GROUP BY
  Weeks.Week_Start_Date, Weeks.Week_End_Date
ORDER BY
  Weeks.Week_Start_Date DESC;