WITH Valid_Customers AS (
    SELECT wcc.ID, wcc.FIRSTNAME, wcc.LASTNAME, wcc.EMAIL, wrcs.PLANID, wrcs.CREATEDAT
    FROM WALDO_CUSTOMERS.CUSTOMER wcc
    JOIN WALDO_RENEWALS.CUSTOMERSUBSCRIPTION wrcs ON wcc.ID = wrcs.CUSTOMERID
    WHERE wcc.EMAIL LIKE '%@%'
      AND wcc.EMAIL NOT LIKE '%@hiwaldo%'
      AND wcc.EMAIL NOT LIKE '%no-mail%'
      AND LOWER(wcc.FIRSTNAME) NOT LIKE '%test%'
      AND LOWER(wcc.FIRSTNAME) NOT LIKE '%-%'
      AND LOWER(wcc.FIRSTNAME) NOT LIKE '%.%'
      AND LOWER(wcc.LASTNAME) NOT LIKE '%test%'
      AND LOWER(wcc.LASTNAME) NOT LIKE '%-%'
      AND LOWER(wcc.LASTNAME) NOT LIKE '%.%'
      AND NOT REGEXP_LIKE(wcc.FIRSTNAME, '[0-9]')
      AND NOT REGEXP_LIKE(wcc.LASTNAME, '[0-9]')
--       AND TO_CHAR(wrcs.CREATEDAT, 'YYYY-MM-DD') >= '2021-06-22'
      AND wcc.FIRSTNAME IS NOT NULL
),
subscription_orders AS (
SELECT DISTINCT
   wooc.CUSTOMERID, woo.ID, opv.NAME, woo.PLANID, opv.QUANTITY

   -- DISTINCT wooc.CUSTOMERID, opv.ORDERID, opv.QUANTITY, opv.PRODUCTVARIANTID, opv.NAME, woo.PLANID
FROM WALDO_ORDERS."ORDER" woo
JOIN WALDO_ORDERS.ORDERPRODUCTVARIANT opv on woo.ID = opv.ORDERID
JOIN WALDO_ORDERS.ORDERCUSTOMER wooc on opv.ORDERID = wooc.ORDERID
JOIN WALDO_ORDERS.CHARGE woc on woo.ID = woc.ORDERID
WHERE (lower(opv.NAME) LIKE '%vitamin%' OR lower(opv.NAME) LIKE '%hydra boost%')
    AND lower(opv.NAME) NOT LIKE '%trial%'
AND wooc.CUSTOMERID IN (SELECT DISTINCT vc.ID FROM Valid_Customers vc)
AND woc.STATUS = 'SUCCESS'
AND woo.STATUS IN ('SUCCESS','APPROVED','DISPATCHING', 'AUTHORISING', 'PENDING')
AND TO_CHAR(woc.CREATEDAT, 'YYYY-MM-DD') >= '2021-06-22'
-- AND wooc.CUSTOMERID = 243991
)
SELECT so.CUSTOMERID, so.PLANID, cp.TITLE, SUM(so.QUANTITY) as total_orders
    FROM subscription_orders so
    JOIN WALDO_CATALOG.CATALOGPLAN cp on so.PLANID = cp.ID
--     WHERE so.CUSTOMERID = 75480
-- WHERE lower(cp.TITLE) LIKE '%quart%'
GROUP BY so.CUSTOMERID, cp.TITLE, so.PLANID
ORDER BY total_orders desc;