-- Dates from 2021-06-22 to 2021-12-31
-- 2022-01-01 to 2022-12-31
-- 2023-01-01 to 2023-12-31
-- 2024-01-01 to 2024-06-10 (Current Last Date)
WITH Valid_Customers AS (
SELECT wcc.ID, wcc.FIRSTNAME, wcc.LASTNAME, wcc.EMAIL
FROM WALDO_CUSTOMERS.CUSTOMER wcc
WHERE wcc.EMAIL LIKE '%@%'
AND wcc.EMAIL NOT LIKE '%@hiwaldo%'
AND wcc.EMAIL NOT LIKE '%no-mail%'
AND LOWER(wcc.FIRSTNAME) NOT LIKE '%test%'
AND LOWER(wcc.FIRSTNAME) NOT LIKE '%-%'
AND LOWER(wcc.FIRSTNAME) NOT LIKE '%.%'
AND LOWER(wcc.LASTNAME) NOT LIKE '%test%'
AND LOWER(wcc.LASTNAME) NOT LIKE '%-%'
AND LOWER(wcc.LASTNAME) NOT LIKE '%.%'
AND NOT REGEXP_LIKE(wcc.FIRSTNAME, '[0-9]')
AND NOT REGEXP_LIKE(wcc.LASTNAME, '[0-9]')
AND wcc.FIRSTNAME IS NOT NULL
),
Hydration_BLG AS (
SELECT woov.CREATEDAT, woov.NAME, wooc.CUSTOMERID, woo.PLANID, woo.ID, woov.QUANTITY, woo.STATUS, wcc.REGION
FROM WALDO_ORDERS.ORDERPRODUCTVARIANT woov
LEFT JOIN WALDO_ORDERS.ORDERCUSTOMER wooc on woov.ORDERID = wooc.ORDERID
LEFT JOIN WALDO_CUSTOMERS.CUSTOMER wcc on wooc.CUSTOMERID = wcc.ID
LEFT JOIN WALDO_ORDERS."ORDER" woo on woov.ORDERID = woo.ID
WHERE (PRODUCTVARIANTID = 216) -- 201
AND TO_CHAR(woov.CREATEDAT, 'YYYY-MM-DD') BETWEEN '2023-01-01' AND  '2023-12-31'
AND woo.STATUS = 'SUCCESS' AND wcc.ID IN (SELECT DISTINCT vc.ID FROM Valid_Customers vc)
ORDER BY wooc.CUSTOMERID, woov.CREATEDAT
)
SELECT
    --'2024-01-01' as start_date, TO_CHAR(CURRENT_DATE(), 'YYYY-MM-DD') as end_date, COUNT(DISTINCT hb.CUSTOMERID) as distinct_customers, SUM(hb.QUANTITY) as total_orders
    hb.CUSTOMERID, COALESCE(ccp.TITLE, 'N/A') as PLAN_TITLE, hb.REGION, COUNT(hb.CREATEDAT) as "total_orders Hydration Drops" -- sum(hb.QUANTITY) as "totalcount",
FROM Hydration_BLG hb
LEFT JOIN WALDO_CATALOG.CATALOGPLAN ccp on hb.PLANID = ccp.ID
GROUP BY hb.CUSTOMERID, ccp.TITLE, hb.REGION
ORDER BY COUNT(hb.CREATEDAT) desc;