-- Dates from 2021-06-22 to 2021-12-31
-- 2022-01-01 to 2022-12-31
-- 2023-01-01 to 2023-12-31
-- 2024-01-01 to 2024-06-10 (Current Last Date)
WITH Valid_Customers AS (
SELECT wcc.ID, wcc.FIRSTNAME, wcc.LASTNAME, wcc.EMAIL
FROM WALDO_CUSTOMERS.CUSTOMER wcc
WHERE wcc.EMAIL LIKE '%@%'
AND wcc.EMAIL NOT LIKE '%@hiwaldo%'
AND wcc.EMAIL NOT LIKE '%no-mail%'
AND LOWER(wcc.FIRSTNAME) NOT LIKE '%test%'
AND LOWER(wcc.FIRSTNAME) NOT LIKE '%-%'
AND LOWER(wcc.FIRSTNAME) NOT LIKE '%.%'
AND LOWER(wcc.LASTNAME) NOT LIKE '%test%'
AND LOWER(wcc.LASTNAME) NOT LIKE '%-%'
AND LOWER(wcc.LASTNAME) NOT LIKE '%.%'
AND NOT REGEXP_LIKE(wcc.FIRSTNAME, '[0-9]')
AND NOT REGEXP_LIKE(wcc.LASTNAME, '[0-9]')
AND wcc.FIRSTNAME IS NOT NULL
),
Hydration_BLG AS (
SELECT wcc.REGION,
       SUM(CASE WHEN PRODUCTVARIANTID = 216 THEN woov.QUANTITY ELSE 0 END) as quantity_HD,
       SUM(CASE WHEN PRODUCTVARIANTID = 201 THEN woov.QUANTITY ELSE 0 END) as quantity_BLG
FROM WALDO_ORDERS.ORDERPRODUCTVARIANT woov
LEFT JOIN WALDO_ORDERS.ORDERCUSTOMER wooc on woov.ORDERID = wooc.ORDERID
LEFT JOIN WALDO_CUSTOMERS.CUSTOMER wcc on wooc.CUSTOMERID = wcc.ID
LEFT JOIN WALDO_ORDERS."ORDER" woo on woov.ORDERID = woo.ID
WHERE TO_CHAR(woov.CREATEDAT, 'YYYY-MM-DD') BETWEEN '2021-06-22' AND '2021-12-31'
AND woo.STATUS = 'SUCCESS' AND wcc.ID IN (SELECT DISTINCT vc.ID FROM Valid_Customers vc)
GROUP BY wcc.REGION
)
SELECT
    '2021-06-22' as start_date, '2021-12-31' as end_date, hb.REGION, quantity_HD, quantity_BLG
FROM Hydration_BLG hb
group by start_date,end_date,hb.REGION;